# docker-compose.yml
version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - '$PORT:$PORT'
    volumes:
      - .:/app/
      - /app/node_modules

  # postgres:
  #   image: postgres:latest
  #   ports:
  #     - '35432:5432'
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: pass
  #     POSTGRES_DB: db
